source 'https://rubygems.org'
gem 'sinatra', '~>1.3.3'
gem 'sinatra-contrib', '~>1.3.1'
gem 'haml', '~>3.1.7'
gem 'require_relative', '~>1.0.3'
gem 'bcrypt-ruby', '~>3.0.1'
gem 'rcov', '~>1.0.0'
gem 'rdiscount', '~>1.6.8'
gem 'less', '~>2.2.2'
gem 'thin', '~>1.5.0'
gem 'shotgun', '~>0.9'
gem 'rbtree', '~> 0.3.0'
gem 'rand62'
gem 'tlsmail'